### ISSUE TITLE
Complex ID not exported

### ISSUE THREAD

**Issue by mikessh** [antigenomics/vdjdb-web#31]
From https://github.com/antigenomics/vdjdb-db/issues/244

> When using the web interface, paired records are visible through the "Gene" column in the result table. However, when I export the data to a text file, this column is missing so I have no way of finding paired entries. Could you add this field to the export or provide an alternative way of accessing the information?

@bvdmitri can you please elaborate?

**Comment by bvdmitri** [comment]
@mikessh, @janwilamowski 
Of course, I will update export feature in our next vdjdb-web server update.

**Comment by janwilamowski** [comment]
Great, thanks! Can you estimate when that should be available?

**Comment by bvdmitri** [comment]
@janwilamowski 
The next big update is scheduled for January. 
But i think we can implement this feature regardless of the scheduled update and it will be available this week.

**Comment by bvdmitri** [comment]
@janwilamowski
Glad to say that paired records export feature was implemented [here](https://github.com/antigenomics/vdjdb-web/commit/10ef28e4289a6ecbec89978ad919e3cd3c064c09).
You can try it via [web-interface](https://vdjdb.cdr3.net/).
Additional records will be added after the main table. Also a new column ('complex.id') has been added. Paired records have the same complex.id.

**Comment by janwilamowski** [comment]
looks good, thanks for fixing this so quickly!
