### ISSUE TITLE
Logging in creates a HTTP500 error

### ISSUE THREAD

**Issue by NigelDyer** [antigenomics/vdjdb-web#52]
I have registered on vdjweb with a .ac.uk Email address, but when I clicked on the Email I get a web page that says "Invalid verification token".  When I try to return to the website I get a HTTP500 error.  I can see the website if I clear cookies, but when I try logging in I get the same HTTP500 error.   I tried registering with a .com Email address and this time it was happy with the link on the registration Email, but I then I got HTTP500 errors if I tried logging on to use the site.  This also happens with Chrome on Windows 10, Edge on Windows 10 and Chrome on an Apple mac.  Safari on an Apple mac returns a blank screen after logging on.

**Comment by bvdmitri** [comment]
@NigelDyer Hello, we reviewed your issue and also I checked the server logs and maybe I found the problem. Server send you a HTTP500 error because it cannot encode your cookies in a valid way, but it still needs further investigation. I'll try to figure it out and make fix as soon as possible. Can you also send me your email and login you are trying to use on our website?

```
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
java.lang.IllegalArgumentException: Cookie value contains an invalid char:
```

**Comment by NigelDyer** [comment]
Hi
I tried two email addresses.   The first was nigel.dyer@warwick.ac.uk<mailto:nigel.dyer@warwick.ac.uk>, which gave me an "Invalid verification token". Error when I clicked on the link in the response Email.   I then tried registering with nigel@coherentwatersystems.com<mailto:nigel@coherentwatersystems.com>, after clearing cookies and this time it appeared happy when I clicked on the link in the Email, but when I then tried to use the website I got the HTTP500 error as was the case with the first Email.
Thanks
Nigel

**Comment by bvdmitri** [comment]
@NigelDyer 
Hello again, i made small fix for cookie storage logic on backend and deployed a new version of vdjdb-web on server and hoping it will help. Can you please try to log-in with nigel@coherentwatersystems.com email and tell us has error disappeared or not. You also can try to register again with your .ac.uk email.

**Comment by NigelDyer** [comment]
I can now login with both Email addresses.
Thanks
Nigel

**Comment by bvdmitri** [comment]
@NigelDyer 
Glad to hear that.
Thank you for posting this issue. Closing it as resolved.
Best wishes,
Dmitry B.
