### ISSUE TITLE
No pair information export

### ISSUE THREAD

**Issue by almog6kUNO** [antigenomics/vdjdb-web#58]
Hello,

When using the export function with pair gene export enabled using the web interface export function, the data does not contain any pair information.

**Comment by bvdmitri** [comment]
Hello,

Just checked export feature and it works as expected. The column `complex.id` contains pairing information. TRA and TRB that share an id in the list provided in this columns are known to be paired in one of the publications. If there is no information about paired record in database the `complex.id` field will be equal to `0` in the exported output data.

**Comment by almog6kUNO** [comment]
Yes. Thank you.

**Comment by bvdmitri** [comment]
@almog6kUNO Thank you for your feedback! 
If you have any other questions don’t hesitate to open a new issuen
