### ISSUE TITLE
Extremely slow TSV export

### ISSUE THREAD

**Issue by mikessh** [antigenomics/vdjdb-web#62]
Likely due to the mechanism we use to fetch paired records, see https://github.com/antigenomics/vdjdb-db/issues/308

**Comment by bvdmitri** [comment]
Dear @beyondpie,

Thank you for your feedback.
Indeed, there was a performance regression in our TSV export backend.
We have reimplemented export's feature internal algorithm to make it more efficient and also added a loading label. You can now try to export large datasets with the Web UI on https://vdjdb.cdr3.net/search.

**Comment by beyondpie** [comment]
@mikessh @bvdmitri 
Hi, guys,
Thanks a lot for your efforts! Now it seems quite good for me.
Thanks again.
Songpeng
